project:
  name: export_market_return_202410_100

date:
  start: 20241022
  end: 20241031

universe:
  source_csv: ../FactorModel/data/raw/factor_features_202410_100.csv
  date_col: date
  securityid_col: securityid

database:
  table: "`500ms`.`{date}`"

  securityid_col: SecurityID
  time_col: datetime

  bid1_col: bidprice1
  ask1_col: askprice1

  bid1_volume_col: bidvolume1
  ask1_volume_col: askvolume1

  date_filter_col: ""

  securityid_type: string
  query_chunk_size: 50
  price_scale: 100.0

limit:
  enable: true
  table: "`A_share_Limit`.`{date}`"
  securityid_col: SecurityID
  securityid_type: int
  limit_up_col: limitUpPrice
  limit_down_col: limitDownPrice
  price_scale: 100.0

return:
  horizons: [30, 60, 90, 120]
  drop_nan_returns: true

output:
  csv_path: ../PricingModel/data/market_return_202410_100.csv
  error_log_path: ../PricingModel/data/market_return_202410_100_errors.txt