# -*- coding: utf-8 -*-
"""
Generate two final gradual-build charts with a common start time:

1) Stock-only NAV, after the initial gradual position-building window is removed.
2) Stock + CSI1000 futures overlay NAV, same start time and same benchmark.

Default use case:
- v6_mild_smooth T+1-aware optimizer
- stock curve generated by plot_tplus1_aware_nav_from_shares.py
- futures file: csi1000_im_minute_20241217_20250114.csv

Key convention:
- The strategy is allowed to build positions gradually from 09:30.
- Reporting starts only after the stock gross is sufficiently built, usually around 10:21.
- Both stock-only and stock+futures charts use exactly the same start timestamp.
- Futures overlay fills residual exposure: futures_gross = max(target_total_gross - stock_gross, 0).
- Futures is adjusted only at stock rebalance timestamps, not every minute.
"""

import argparse
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def read_any(path: str) -> pd.DataFrame:
    p = Path(path)
    suf = "".join(p.suffixes).lower()
    if suf.endswith(".parquet"):
        return pd.read_parquet(p)
    if suf.endswith(".csv") or suf.endswith(".csv.gz"):
        return pd.read_csv(p, low_memory=False)
    raise ValueError(f"Unsupported file type: {p}")


def pick_col(df: pd.DataFrame, candidates, required=True, name="column"):
    for c in candidates:
        if c in df.columns:
            return c
    lower = {c.lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in lower:
            return lower[c.lower()]
    if required:
        raise KeyError(f"Cannot find {name}. candidates={candidates}; columns={list(df.columns)}")
    return None


def compound(ret) -> float:
    x = pd.Series(ret).replace([np.inf, -np.inf], np.nan).fillna(0.0)
    return float((1.0 + x).prod() - 1.0)


def daily_sharpe(df: pd.DataFrame, actual_col: str, bench_col: str) -> float:
    daily = (
        df.groupby("date", as_index=False)
        .agg(
            actual_day=(actual_col, compound),
            bench_day=(bench_col, compound),
        )
    )
    daily["excess"] = daily["actual_day"] - daily["bench_day"]
    x = daily["excess"].dropna()
    if len(x) <= 1 or x.std(ddof=1) <= 1e-12:
        return np.nan
    return float(x.mean() / x.std(ddof=1) * np.sqrt(252.0))


def normalize_stock_curve(path: str) -> pd.DataFrame:
    raw = read_any(path)
    dt_col = pick_col(raw, ["datetime", "execution_datetime", "dt", "ts"], name="datetime")
    date_col = pick_col(raw, ["date", "execution_date"], required=False, name="date")

    out = raw.copy()
    out["datetime"] = pd.to_datetime(out[dt_col])
    if date_col is not None:
        out["date"] = pd.to_numeric(out[date_col], errors="coerce").astype(int)
    else:
        out["date"] = out["datetime"].dt.strftime("%Y%m%d").astype(int)

    actual_ret_col = pick_col(out, ["actual_ret", "stock_actual_ret", "strategy_ret"], name="stock actual return")
    benchmark_ret_col = pick_col(out, ["benchmark_ret", "bench_ret", "benchmark_return"], name="benchmark return")

    # For exposure to be held after rebalance, prefer after-to-equity. Fallback to prev-to-equity.
    gross_after_col = pick_col(
        out,
        ["gross_after_to_equity", "actual_gross_after", "actual_gross", "stock_gross"],
        required=False,
        name="gross after",
    )
    gross_prev_col = pick_col(
        out,
        ["gross_prev_to_equity", "held_gross_prev", "avg_gross_prev_to_equity", "gross_prev_to_capital"],
        required=False,
        name="gross prev",
    )

    if gross_after_col is not None:
        stock_gross = pd.to_numeric(out[gross_after_col], errors="coerce")
    elif gross_prev_col is not None:
        stock_gross = pd.to_numeric(out[gross_prev_col], errors="coerce")
    else:
        raise KeyError("Cannot find stock gross column")

    turnover_col = pick_col(out, ["turnover_weight", "turnover_to_capital", "turnover"], required=False, name="turnover")
    total_cost_col = pick_col(out, ["total_cost", "cost", "fee"], required=False, name="total cost")

    df = pd.DataFrame({
        "date": out["date"].astype(int),
        "datetime": out["datetime"],
        "stock_actual_ret": pd.to_numeric(out[actual_ret_col], errors="coerce").fillna(0.0),
        "benchmark_ret": pd.to_numeric(out[benchmark_ret_col], errors="coerce").fillna(0.0),
        "stock_gross": stock_gross.fillna(0.0).clip(lower=0.0),
    })

    if turnover_col is not None:
        df["turnover_weight"] = pd.to_numeric(out[turnover_col], errors="coerce").fillna(0.0)
    else:
        df["turnover_weight"] = 0.0

    if total_cost_col is not None:
        df["total_cost"] = pd.to_numeric(out[total_cost_col], errors="coerce").fillna(0.0)
    else:
        df["total_cost"] = 0.0

    df = df.sort_values(["date", "datetime"]).reset_index(drop=True)
    df["minute_dt"] = df["datetime"].dt.floor("min")
    return df


def normalize_futures(path: str) -> pd.DataFrame:
    raw = read_any(path)
    dt_col = pick_col(raw, ["datetime", "dt", "ts", "timestamp"], name="futures datetime")
    date_col = pick_col(raw, ["date", "trading_date"], required=False, name="futures date")
    price_col = pick_col(raw, ["futures_price", "last_price", "lastprice", "close", "price", "mid_price", "tmid"], name="futures price")
    contract_col = pick_col(raw, ["contract", "SecurityID", "securityid", "symbol"], required=False, name="contract")

    df = pd.DataFrame({
        "datetime": pd.to_datetime(raw[dt_col]),
        "fut_price": pd.to_numeric(raw[price_col], errors="coerce"),
    })
    if date_col is not None:
        df["date"] = pd.to_numeric(raw[date_col], errors="coerce").astype(int)
    else:
        df["date"] = df["datetime"].dt.strftime("%Y%m%d").astype(int)
    if contract_col is not None:
        df["contract"] = raw[contract_col].astype(str)
    else:
        df["contract"] = ""

    df = df.dropna(subset=["datetime", "fut_price"])
    df = df[df["fut_price"] > 0].sort_values(["date", "datetime"]).reset_index(drop=True)
    df["minute_dt"] = df["datetime"].dt.floor("min")
    return df


def find_start_index(stock: pd.DataFrame, target_total_gross: float, ratio: float, min_consecutive: int) -> int:
    threshold = float(target_total_gross) * float(ratio)
    cond = (stock["stock_gross"] >= threshold).to_numpy()
    need = max(1, int(min_consecutive))
    for i in range(0, len(cond) - need + 1):
        if cond[i:i + need].all():
            return i
    return 0


def rebase_stock_only(stock: pd.DataFrame, start_idx: int) -> pd.DataFrame:
    df = stock.iloc[start_idx:].copy().reset_index(drop=True)
    df["bar_index"] = np.arange(len(df))
    df["stock_actualret"] = (1.0 + df["stock_actual_ret"]).cumprod() - 1.0
    df["benchmarkret"] = (1.0 + df["benchmark_ret"]).cumprod() - 1.0
    df["stock_alpharet"] = df["stock_actualret"] - df["benchmarkret"]
    return df


def align_futures(stock: pd.DataFrame, futures: pd.DataFrame) -> pd.DataFrame:
    left = stock.sort_values(["date", "minute_dt"]).reset_index(drop=True)
    right = futures.sort_values(["date", "minute_dt"]).reset_index(drop=True)
    merged = pd.merge_asof(
        left,
        right[["date", "minute_dt", "fut_price", "contract"]],
        on="minute_dt",
        by="date",
        direction="backward",
        tolerance=pd.Timedelta("10min"),
    )
    merged["fut_price"] = merged.groupby("date")["fut_price"].ffill().bfill()
    merged["contract"] = merged.groupby("date")["contract"].ffill().bfill().fillna("")
    merged["fut_ret"] = merged.groupby("date")["fut_price"].pct_change().replace([np.inf, -np.inf], np.nan).fillna(0.0)
    return merged


def build_overlay(stock_aligned: pd.DataFrame, futures: pd.DataFrame, target_total_gross: float, futures_fee_rate: float, futures_leverage: float, zero_initial_futures_cost: bool) -> pd.DataFrame:
    df = align_futures(stock_aligned, futures)

    df["target_total_gross"] = float(target_total_gross)
    df["desired_futures_overlay_gross"] = (df["target_total_gross"] - df["stock_gross"]).clip(lower=0.0)

    rebalance_mask = df["turnover_weight"].fillna(0.0).abs() > 1e-12
    if len(df) > 0:
        rebalance_mask.iloc[0] = True

    df["futures_overlay_gross"] = np.nan
    df.loc[rebalance_mask, "futures_overlay_gross"] = df.loc[rebalance_mask, "desired_futures_overlay_gross"]
    df["futures_overlay_gross"] = df["futures_overlay_gross"].ffill().fillna(0.0)

    # PnL uses previous futures holding. At the first reported minute, assume futures was already in place.
    df["futures_overlay_gross_prev"] = df["futures_overlay_gross"].shift(1)
    if len(df) > 0:
        df.loc[df.index[0], "futures_overlay_gross_prev"] = df.loc[df.index[0], "futures_overlay_gross"]
    df["futures_overlay_gross_prev"] = df["futures_overlay_gross_prev"].fillna(0.0)

    prev_overlay = df["futures_overlay_gross"].shift(1).fillna(df["futures_overlay_gross"])
    df["futures_turnover_gross"] = 0.0
    df.loc[rebalance_mask, "futures_turnover_gross"] = (df.loc[rebalance_mask, "futures_overlay_gross"] - prev_overlay.loc[rebalance_mask]).abs()
    if zero_initial_futures_cost and len(df) > 0:
        df.loc[df.index[0], "futures_turnover_gross"] = 0.0

    df["futures_fee_return"] = df["futures_turnover_gross"] * float(futures_fee_rate)
    df["futures_pnl_return"] = df["futures_overlay_gross_prev"] * df["fut_ret"]
    df["actual_ret_with_futures"] = df["stock_actual_ret"] + df["futures_pnl_return"] - df["futures_fee_return"]
    df["alpha_ret_with_futures"] = df["actual_ret_with_futures"] - df["benchmark_ret"]
    df["futures_margin_used"] = df["futures_overlay_gross"] / float(futures_leverage)

    df["bar_index"] = np.arange(len(df))
    df["actualret_with_futures"] = (1.0 + df["actual_ret_with_futures"]).cumprod() - 1.0
    df["benchmarkret"] = (1.0 + df["benchmark_ret"]).cumprod() - 1.0
    df["alpharet_with_futures"] = df["actualret_with_futures"] - df["benchmarkret"]
    return df


def summary_stock(df: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame([{
        "start_datetime": str(df["datetime"].iloc[0]),
        "end_datetime": str(df["datetime"].iloc[-1]),
        "strategy_return": compound(df["stock_actual_ret"]),
        "benchmark_return": compound(df["benchmark_ret"]),
        "alpha_return": compound(df["stock_actual_ret"]) - compound(df["benchmark_ret"]),
        "daily_excess_sharpe": daily_sharpe(df, "stock_actual_ret", "benchmark_ret"),
        "avg_stock_gross": float(df["stock_gross"].mean()),
        "turnover_weight": float(df["turnover_weight"].sum()),
        "total_cost": float(df["total_cost"].sum()),
        "n_minutes": int(len(df)),
        "n_days": int(df["date"].nunique()),
    }])


def summary_overlay(df: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame([{
        "start_datetime": str(df["datetime"].iloc[0]),
        "end_datetime": str(df["datetime"].iloc[-1]),
        "strategy_return": compound(df["actual_ret_with_futures"]),
        "benchmark_return": compound(df["benchmark_ret"]),
        "alpha_return": compound(df["actual_ret_with_futures"]) - compound(df["benchmark_ret"]),
        "daily_excess_sharpe": daily_sharpe(df, "actual_ret_with_futures", "benchmark_ret"),
        "avg_stock_gross": float(df["stock_gross"].mean()),
        "avg_futures_overlay_gross": float(df["futures_overlay_gross"].mean()),
        "avg_margin_used": float(df["futures_margin_used"].mean()),
        "total_futures_turnover_gross": float(df["futures_turnover_gross"].sum()),
        "total_futures_fee_return": float(df["futures_fee_return"].sum()),
        "n_minutes": int(len(df)),
        "n_days": int(df["date"].nunique()),
    }])


def make_ticks(df):
    first = df.groupby("date", as_index=False).first()[["date", "bar_index"]]
    step = max(1, len(first) // 10)
    ticks = first.iloc[::step]
    return ticks["bar_index"].tolist(), ticks["date"].astype(str).tolist()


def fmt_pct(x):
    return f"{x:.2%}" if pd.notna(x) else "NA"


def fmt_num(x):
    return f"{x:.2f}" if pd.notna(x) else "NA"


def plot_stock(df: pd.DataFrame, summ: pd.DataFrame, out_png: Path, title: str):
    fig = plt.figure(figsize=(18, 8))
    gs = fig.add_gridspec(1, 2, width_ratios=[5.5, 1.3], wspace=0.08)
    ax = fig.add_subplot(gs[0, 0])
    box = fig.add_subplot(gs[0, 1])
    box.axis("off")

    ax.plot(df["bar_index"], df["stock_actualret"] * 100.0, label="stock-only actualret")
    ax.plot(df["bar_index"], df["benchmarkret"] * 100.0, label="benchmarkret")
    ax.plot(df["bar_index"], df["stock_alpharet"] * 100.0, label="stock-only alpharet")
    ax.axhline(0.0, linestyle="--", linewidth=0.8)
    ax.grid(True, alpha=0.3)
    ax.set_title(title, fontsize=16, fontweight="bold")
    ax.set_ylabel("cumulative return (%)")
    ax.set_xlabel("trading minute index, gradual build window removed")
    ticks, labels = make_ticks(df)
    ax.set_xticks(ticks)
    ax.set_xticklabels(labels, rotation=45, ha="right")
    ax.legend(loc="lower left")

    r = summ.iloc[0]
    text = (
        "Summary\n\n"
        f"Strategy Return\n{fmt_pct(r['strategy_return'])}\n\n"
        f"Benchmark Return\n{fmt_pct(r['benchmark_return'])}\n\n"
        f"Alpha Return\n{fmt_pct(r['alpha_return'])}\n\n"
        f"Daily Excess Sharpe\n{fmt_num(r['daily_excess_sharpe'])}"
    )
    box.text(0.02, 0.95, text, va="top", ha="left", fontsize=12, bbox=dict(boxstyle="round,pad=0.5", facecolor="white", edgecolor="0.6"))
    fig.tight_layout()
    fig.savefig(out_png, dpi=180, bbox_inches="tight")
    plt.close(fig)


def plot_overlay(df: pd.DataFrame, summ: pd.DataFrame, out_png: Path, title: str):
    fig = plt.figure(figsize=(18, 8))
    gs = fig.add_gridspec(1, 2, width_ratios=[5.5, 1.3], wspace=0.08)
    ax = fig.add_subplot(gs[0, 0])
    box = fig.add_subplot(gs[0, 1])
    box.axis("off")

    ax.plot(df["bar_index"], df["actualret_with_futures"] * 100.0, label="actualret with futures")
    ax.plot(df["bar_index"], df["benchmarkret"] * 100.0, label="benchmarkret")
    ax.plot(df["bar_index"], df["alpharet_with_futures"] * 100.0, label="alpharet")
    ax.axhline(0.0, linestyle="--", linewidth=0.8)
    ax.grid(True, alpha=0.3)
    ax.set_title(title, fontsize=16, fontweight="bold")
    ax.set_ylabel("cumulative return (%)")
    ax.set_xlabel("trading minute index, gradual build window removed")
    ticks, labels = make_ticks(df)
    ax.set_xticks(ticks)
    ax.set_xticklabels(labels, rotation=45, ha="right")
    ax.legend(loc="lower left")

    r = summ.iloc[0]
    text = (
        "Summary\n\n"
        f"Strategy Return\n{fmt_pct(r['strategy_return'])}\n\n"
        f"Benchmark Return\n{fmt_pct(r['benchmark_return'])}\n\n"
        f"Alpha Return\n{fmt_pct(r['alpha_return'])}\n\n"
        f"Daily Excess Sharpe\n{fmt_num(r['daily_excess_sharpe'])}"
    )
    box.text(0.02, 0.95, text, va="top", ha="left", fontsize=12, bbox=dict(boxstyle="round,pad=0.5", facecolor="white", edgecolor="0.6"))
    fig.tight_layout()
    fig.savefig(out_png, dpi=180, bbox_inches="tight")
    plt.close(fig)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stock-curve", required=True)
    ap.add_argument("--futures", required=True)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--tag", default="v6_gradual_1021")
    ap.add_argument("--target-total-gross", type=float, default=1.0)
    ap.add_argument("--start-gross-ratio", type=float, default=0.90)
    ap.add_argument("--min-consecutive", type=int, default=5)
    ap.add_argument("--futures-fee-rate", type=float, default=0.000023)
    ap.add_argument("--futures-leverage", type=float, default=10.0)
    ap.add_argument("--zero-initial-futures-cost", type=int, default=1)
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    stock_full = normalize_stock_curve(args.stock_curve)
    fut = normalize_futures(args.futures)

    start_idx = find_start_index(stock_full, args.target_total_gross, args.start_gross_ratio, args.min_consecutive)
    stock = rebase_stock_only(stock_full, start_idx)
    overlay = build_overlay(
        stock,
        fut,
        target_total_gross=args.target_total_gross,
        futures_fee_rate=args.futures_fee_rate,
        futures_leverage=args.futures_leverage,
        zero_initial_futures_cost=bool(args.zero_initial_futures_cost),
    )

    stock_s = summary_stock(stock)
    overlay_s = summary_overlay(overlay)

    stock_curve = out_dir / f"{args.tag}_stock_only_curve.csv"
    stock_summary = out_dir / f"{args.tag}_stock_only_summary.csv"
    stock_png = out_dir / f"{args.tag}_stock_only_nav.png"
    overlay_curve = out_dir / f"{args.tag}_stock_plus_futures_curve.csv"
    overlay_summary = out_dir / f"{args.tag}_stock_plus_futures_summary.csv"
    overlay_png = out_dir / f"{args.tag}_stock_plus_futures_nav.png"

    stock.to_csv(stock_curve, index=False)
    stock_s.to_csv(stock_summary, index=False)
    overlay.to_csv(overlay_curve, index=False)
    overlay_s.to_csv(overlay_summary, index=False)

    plot_stock(stock, stock_s, stock_png, "Stock-Only: Gradual Position Building, 10:21 Start")
    plot_overlay(overlay, overlay_s, overlay_png, "T+1-aware Pure-CS NAV with CSI1000 Futures Overlay, 10:21 Start")

    print("===== stock-only summary =====")
    print(stock_s.T.to_string(header=False))
    print("\n===== stock + futures summary =====")
    print(overlay_s.T.to_string(header=False))
    print("\n[start]")
    print(stock["datetime"].iloc[0])
    print("\n[saved]")
    print(stock_curve)
    print(stock_summary)
    print(stock_png)
    print(overlay_curve)
    print(overlay_summary)
    print(overlay_png)


if __name__ == "__main__":
    main()
